### ISSUE TITLE
ModuleNotFoundError: No module named 'LoginRadius.api' when running demo

### ISSUE THREAD

**Issue by Sudhanshu-Dubey14** [LoginRadius/python-sdk#36]
If we follow the README, then running the demo gives the following error:

```
[sudhanshu@archlinux demo]$ python app.py 
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from user import user
  File "/run/media/sudhanshu/Thunder/Repos/LoginRadius_python/demo/user.py", line 2, in <module>
    from lr import loginradius
  File "/run/media/sudhanshu/Thunder/Repos/LoginRadius_python/demo/lr.py", line 1, in <module>
    from LoginRadius import LoginRadius as LR
  File "/run/media/sudhanshu/Thunder/Repos/LoginRadius_python/demo/LoginRadius/__init__.py", line 43, in <module>
    from LoginRadius.api.authentication.authentication_api import AuthenticationApi
ModuleNotFoundError: No module named 'LoginRadius.api'
```

And indeed there is no module named in `api` in `LoginRadius` package inside the `demo` directory because it is for some reason placed in the `Demo` directory.

**Comment by giriraj12000** [comment]
Hi,

It seems this PR is not eligible for hacktoberfest so closing this issue.

Thanks
